# Exception: EFI/OC/config/Laptop/HM77 - HM76 - HM75 - HM70 - UM77 - QM77 - QS77/002 - Laptop - Sandy Bridge UEFI BIOS.plist

[[ACPI.Add]]
Comment = ""
Enabled = true
Path = "SSDT-EC-LAPTOP.aml"

[[ACPI.Add]]
Comment = ""
Enabled = true
Path = "SSDT-IMEI.aml"

[[ACPI.Add]]
Comment = ""
Enabled = true
Path = "SSDT-PNLF.aml"

[[ACPI.Add]]
Comment = ""
Enabled = true
Path = "SSDT-XOSI.aml"

[DeviceProperties.Add."PciRoot(0x0)/Pci(0x16,0x0)"]
device-id = "hex:3a1c0000"
