# 2 configs use this alone.

[[ACPI.Add]]
Comment = ""
Enabled = true
Path = "SSDT-EC-LAPTOP.aml"

[[ACPI.Add]]
Comment = ""
Enabled = true
Path = "SSDT-IMEI.aml"

[[ACPI.Add]]
Comment = ""
Enabled = true
Path = "SSDT-PNLF.aml"

[[ACPI.Add]]
Comment = ""
Enabled = true
Path = "SSDT-XOSI.aml"

[DeviceProperties.Add."PciRoot(0x0)/Pci(0x16,0x0)"]
device-id = "hex:3a1c0000"
