# 8 configs use this alone.

[[ACPI.Add]]
Comment = ""
Enabled = true
Path = "SSDT-EC-USBX-DESKTOP.aml"

[[ACPI.Add]]
Comment = ""
Enabled = true
Path = "SSDT-CPUR.aml"

[Booter.Quirks]
SetupVirtualMap = false
