# 3 config, 3 core counts
[[Kernel.Add]]
Arch = "x86_64"
BundlePath = "AppleMCEReporterDisabler.kext"
Comment = "V1.2"
Enabled = true
ExecutablePath = ""
MaxKernel = ""
MinKernel = ""
PlistPath = "Contents/Info.plist"

[[Kernel.Add]]
Arch = "x86_64"
BundlePath = "Lilu.kext"
Comment = "V1.5.9"
Enabled = true
ExecutablePath = "Contents/MacOS/Lilu"
MaxKernel = ""
MinKernel = "8.0.0"
PlistPath = "Contents/Info.plist"

[[Kernel.Add]]
Arch = "x86_64"
BundlePath = "VirtualSMC.kext"
Comment = "V1.2.8"
Enabled = true
ExecutablePath = "Contents/MacOS/VirtualSMC"
MaxKernel = ""
MinKernel = "8.0.0"
PlistPath = "Contents/Info.plist"

[[Kernel.Add]]
Arch = "x86_64"
BundlePath = "WhateverGreen.kext"
Comment = "V1.5.6"
Enabled = true
ExecutablePath = "Contents/MacOS/WhateverGreen"
MaxKernel = ""
MinKernel = "10.0.0"
PlistPath = "Contents/Info.plist"

[[Kernel.Add]]
Arch = "x86_64"
BundlePath = "AppleALC.kext"
Comment = "V1.6.8"
Enabled = true
ExecutablePath = "Contents/MacOS/AppleALC"
MaxKernel = ""
MinKernel = "8.0.0"
PlistPath = "Contents/Info.plist"

[[Kernel.Add]]
Arch = "x86_64"
BundlePath = "XLNCUSBFix.kext"
Comment = ""
Enabled = true
ExecutablePath = ""
MaxKernel = ""
MinKernel = "17.0.0"
PlistPath = "Contents/Info.plist"

[[Kernel.Add]]
Arch = "x86_64"
BundlePath = "AMDRyzenCPUPowerManagement.kext"
Comment = ""
Enabled = false
ExecutablePath = "Contents/MacOS/AMDRyzenCPUPowerManagement"
MaxKernel = ""
MinKernel = "17.0.0"
PlistPath = "Contents/Info.plist"

[[Kernel.Add]]
Arch = "x86_64"
BundlePath = "SMCAMDProcessor.kext"
Comment = ""
Enabled = false
ExecutablePath = "Contents/MacOS/SMCAMDProcessor"
MaxKernel = ""
MinKernel = "17.0.0"
PlistPath = "Contents/Info.plist"

[[Kernel.Patch]]
Arch = "x86_64"
Base = "_cpuid_set_info"
Comment = "algrey | Force cpuid_cores_per_package to constant (user-specified) | 10.13-10.14"
Count = 1
Enabled = true
Find = "hex:c1e81a000000"
Identifier = "kernel"
Limit = 0
Mask = "hex:fffdff000000"
MaxKernel = "18.99.99"
MinKernel = "17.0.0"
Replace = "hex:b8{cores:02x}00000000"
ReplaceMask = "hex:ffffffffff00"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = "_cpuid_set_info"
Comment = "algrey | Force cpuid_cores_per_package to constant (user-specified) | 10.15-11.0"
Count = 1
Enabled = true
Find = "hex:c1e81a000000"
Identifier = "kernel"
Limit = 0
Mask = "hex:fffdff000000"
MaxKernel = "20.99.99"
MinKernel = "19.0.0"
Replace = "hex:ba{cores:02x}00000000"
ReplaceMask = "hex:ffffffffff00"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = "_cpuid_set_info"
Comment = "algrey | Force cpuid_cores_per_package to constant (user-specified) | 12.0-13.2"
Count = 1
Enabled = true
Find = "hex:c1e81a000000"
Identifier = "kernel"
Limit = 0
Mask = "hex:fffdff000000"
MaxKernel = "22.3.99"
MinKernel = "21.0.0"
Replace = "hex:ba{cores:02x}00000090"
ReplaceMask = "hex:"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = "_cpuid_set_info"
Comment = "algrey | Force cpuid_cores_per_package to constant (user-specified) | 13.3+"
Count = 1
Enabled = true
Find = "hex:c1e81a0000"
Identifier = "kernel"
Limit = 0
Mask = "hex:fffdff0000"
MaxKernel = "25.99.99"
MinKernel = "22.4.0"
Replace = "hex:ba{cores:02x}000000"
ReplaceMask = "hex:ffffffffff"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = ""
Comment = "algrey | _commpage_populate | Remove rdmsr | 10.13+"
Count = 1
Enabled = true
Find = "hex:b9a00100000f32"
Identifier = "kernel"
Limit = 0
Mask = "hex:"
MaxKernel = "25.99.99"
MinKernel = "17.0.0"
Replace = "hex:66906690669090"
ReplaceMask = "hex:"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = ""
Comment = "algrey | _cpuid_set_cache_info | Set CPUID proper instead of 4 | 10.13+"
Count = 1
Enabled = true
Find = "hex:b8040000004489f14489"
Identifier = "kernel"
Limit = 0
Mask = "hex:"
MaxKernel = "25.99.99"
MinKernel = "17.0.0"
Replace = "hex:b81d0000804489f14489"
ReplaceMask = "hex:"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = ""
Comment = "algrey | _cpuid_set_generic_info | Remove wrmsr(0x8B) | 10.13+"
Count = 1
Enabled = true
Find = "hex:b98b00000031c031d20f30"
Identifier = "kernel"
Limit = 0
Mask = "hex:"
MaxKernel = "25.99.99"
MinKernel = "17.0.0"
Replace = "hex:6690669066906690669090"
ReplaceMask = "hex:"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = ""
Comment = "algrey | _cpuid_set_generic_info | Replace rdmsr(0x8B) with constant 186 | 10.13+"
Count = 1
Enabled = true
Find = "hex:b98b0000000f32"
Identifier = "kernel"
Limit = 0
Mask = "hex:"
MaxKernel = "25.99.99"
MinKernel = "17.0.0"
Replace = "hex:baba0000006690"
ReplaceMask = "hex:"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = ""
Comment = "algrey | _cpuid_set_generic_info | Set flag=1 | 10.13+"
Count = 1
Enabled = true
Find = "hex:b9170000000f32c1ea1280e207"
Identifier = "kernel"
Limit = 0
Mask = "hex:"
MaxKernel = "25.99.99"
MinKernel = "17.0.0"
Replace = "hex:b201660f1f8400000000006690"
ReplaceMask = "hex:"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = ""
Comment = "algrey | _cpuid_set_generic_info | Disable check to allow leaf7 | 10.13+"
Count = 1
Enabled = true
Find = "hex:003a0f82"
Identifier = "kernel"
Limit = 0
Mask = "hex:"
MaxKernel = "23.99.99"
MinKernel = "17.0.0"
Replace = "hex:00000f82"
ReplaceMask = "hex:"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = ""
Comment = "algrey | _cpuid_set_generic_info | Disable check to allow leaf7 | 15.0+"
Count = 1
Enabled = true
Find = "hex:00050f82"
Identifier = "kernel"
Limit = 0
Mask = "hex:"
MaxKernel = "25.99.99"
MinKernel = "24.0.0"
Replace = "hex:00000f82"
ReplaceMask = "hex:"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = ""
Comment = "algrey | _cpuid_set_info | GenuineIntel to AuthenticAMD | 10.13-11.0"
Count = 1
Enabled = true
Find = "hex:47656e75696e65496e74656c00"
Identifier = "kernel"
Limit = 0
Mask = "hex:"
MaxKernel = "20.99.99"
MinKernel = "17.0.0"
Replace = "hex:41757468656e746963414d4400"
ReplaceMask = "hex:"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = "_cpuid_set_info"
Comment = "Goldfish64, algrey | Bypass GenuineIntel check panic | 12.0+"
Count = 1
Enabled = true
Find = "hex:00000000000031d2b301"
Identifier = "kernel"
Limit = 0
Mask = "hex:000000000000ffffffff"
MaxKernel = "25.99.99"
MinKernel = "21.0.0"
Replace = "hex:90909090909031d2b301"
ReplaceMask = "hex:"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = ""
Comment = "algrey | _cpuid_set_cpufamily | Force CPUFAMILY_INTEL_PENRYN | 10.13-11.2"
Count = 1
Enabled = true
Find = "hex:31db803d00000000067500"
Identifier = "kernel"
Limit = 0
Mask = "hex:ffffffff000000ffffff00"
MaxKernel = "20.3.0"
MinKernel = "17.0.0"
Replace = "hex:bbbc4fea78e95d00000090"
ReplaceMask = "hex:"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = "_cpuid_set_info "
Comment = "algrey | _cpuid_set_cpufamily | Force CPUFAMILY_INTEL_PENRYN | 11.3+"
Count = 1
Enabled = true
Find = "hex:803d000000000675"
Identifier = "kernel"
Limit = 0
Mask = "hex:ffff00000000ffff"
MaxKernel = "25.99.99"
MinKernel = "20.4.0"
Replace = "hex:babc4fea7831dbeb"
ReplaceMask = "hex:"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = ""
Comment = "algrey | _i386_init | Remove 3 rdmsr calls | 10.13+"
Count = 0
Enabled = true
Find = "hex:b9990100000f3248c1e22089c64809d6b9980100000f3248c1e22089c04809c2bf5802310531c94531c0"
Identifier = "kernel"
Limit = 0
Mask = "hex:"
MaxKernel = "25.99.99"
MinKernel = "17.0.0"
Replace = "hex:660f1f840000000000660f1f840000000000660f1f840000000000660f1f840000000000660f1f440000"
ReplaceMask = "hex:"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = ""
Comment = "algrey, XLNC | Remove version check and panic | 10.13+"
Count = 1
Enabled = true
Find = "hex:25fc00000083f813"
Identifier = "kernel"
Limit = 0
Mask = "hex:"
MaxKernel = "25.99.99"
MinKernel = "17.0.0"
Replace = "hex:25fc0000000f1f00"
ReplaceMask = "hex:"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = "__ZN11IOPCIBridge13probeBusGatedEP14probeBusParams"
Comment = "CaseySJ | probeBusGated | Disable 10 bit tags | 12.0+"
Count = 1
Enabled = true
Find = "hex:e0117200"
Identifier = "com.apple.iokit.IOPCIFamily"
Limit = 0
Mask = "hex:f0fffff0"
MaxKernel = "25.99.99"
MinKernel = "21.0.0"
Replace = "hex:00000300"
ReplaceMask = "hex:00000f00"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = "__ZN17IOPCIConfigurator18IOPCIIsHotplugPortEP16IOPCIConfigEntry"
Comment = "CaseySJ | IOPCIIsHotplugPort | Fix PCI bus enumeration on AM5 | 13.0+"
Count = 1
Enabled = false
Find = "hex:8400754b"
Identifier = "com.apple.iokit.IOPCIFamily"
Limit = 0
Mask = "hex:ff00ffff"
MaxKernel = "25.99.99"
MinKernel = "22.0.0"
Replace = "hex:0000eb00"
ReplaceMask = "hex:0000ff00"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = ""
Comment = "Visual | thread_quantum_expire, thread_unblock, thread_invoke | Remove non-monotonic time panic | 12.0+"
Count = 3
Enabled = true
Find = "hex:48000000020000480000580000000f0000000000"
Identifier = "kernel"
Limit = 0
Mask = "hex:ff00000fffffffff0000ff000000ff0000000000"
MaxKernel = "25.99.99"
MinKernel = "21.0.0"
Replace = "hex:0000000000000000000000000000669066906690"
ReplaceMask = "hex:0000000000000000000000000000ffffffffffff"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = ""
Comment = "Visual | thread_invoke, thread_dispatch | Remove non-monotonic time panic | 12.0+"
Count = 2
Enabled = true
Find = "hex:480000800400000f0000000000"
Identifier = "kernel"
Limit = 0
Mask = "hex:480000f0ffffffff0000000000"
MaxKernel = "25.99.99"
MinKernel = "21.0.0"
Replace = "hex:00000000000000669066906690"
ReplaceMask = "hex:00000000000000ffffffffffff"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = ""
Comment = "algrey | _mtrr_update_action | fix PAT | 10.13+"
Count = 0
Enabled = true
Find = "hex:89c081e2ffff00ff81ca00000100b977020000"
Identifier = "kernel"
Limit = 0
Mask = "hex:ffffffffffff0fffffffffffffffffffffffff"
MaxKernel = "23.99.99"
MinKernel = "17.0.0"
Replace = "hex:b977020000b806010700ba060107000f1f4000"
ReplaceMask = "hex:"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = ""
Comment = "Shaneee | _mtrr_update_action | Fix PAT | 10.13+"
Count = 0
Enabled = false
Find = "hex:89c081e2ffff00ff81ca00000100b977020000"
Identifier = "kernel"
Limit = 0
Mask = "hex:ffffffffffff0fffffffffffffffffffffffff"
MaxKernel = "23.99.99"
MinKernel = "17.0.0"
Replace = "hex:b977020000b806060606ba060606060f300f09"
ReplaceMask = "hex:"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = ""
Comment = "Algrey / Zormeister | _mtrr_update_action | Fix PAT | 15.0+"
Count = 0
Enabled = true
Find = "hex:89c081e2ffff00ff81ca000000000f30"
Identifier = "kernel"
Limit = 0
Mask = "hex:ffffffffffffffffffff00000000ffff"
MaxKernel = "25.99.99"
MinKernel = "24.0.0"
Replace = "hex:89c0b806010700ba060107000f309090"
ReplaceMask = "hex:"
Skip = 0

[[Kernel.Patch]]
Arch = "x86_64"
Base = ""
Comment = "Shaneee / Zormeister | _mtrr_update_action | Fix PAT | 15.0+"
Count = 0
Enabled = false
Find = "hex:89c081e2ffff00ff81ca000000000f30"
Identifier = "kernel"
Limit = 0
Mask = "hex:ffffffffffffffffffff00000000ffff"
MaxKernel = "25.99.99"
MinKernel = "24.0.0"
Replace = "hex:89c0b806060606ba060606060f309090"
ReplaceMask = "hex:"
Skip = 0
