"""Human names for the device ids this repository knows.

Everything here keys on `vendor:device` in hex, which is what the kexts match
on and what a machine reports. Nobody reads hex. This puts a name beside it -
"Ellesmere [Radeon RX 470/480/570/580]" rather than 1002:67df - so a catalogue
can be read and filtered by brand.

The names come from the PCI ID Project and the Linux USB project, both of which
publish exactly this as a machine-readable file:

    https://pci-ids.ucw.cz/v2.2/pci.ids
    http://www.linux-usb.org/usb.ids

Only the ids this repository already references are kept. The full lists are
two megabytes of hardware nobody here has a driver for, and vendoring them
whole would be carrying a hardware database to answer nine hundred questions.

    python3 tools/deviceids.py --refresh    # network
    python3 tools/deviceids.py 8086:1559    # what one id is called
"""
import argparse
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ocgen

PCI_SOURCE = 'https://pci-ids.ucw.cz/v2.2/pci.ids'
# hwdata, not linux-usb.org. The file served there carries no licence
# header at all, and in this repository "none stated" is the absence of
# permission rather than a permissive default. hwdata ships the same list
# and states one for it: GPL-2-or-later, or the XFree86 1.0 licence.
USB_SOURCE = ('https://raw.githubusercontent.com/vcrhonek/hwdata/'
              'master/usb.ids')
TABLE = Path('data/deviceids.toml')

HEADER = """# What each device id is called.
#
# Generated by tools/deviceids.py --refresh.
#
# PCI names come from the PCI ID Project, whose file states its own licence:
# "either the GNU General Public License (version 2 or higher) or the 3-clause
# BSD License".
#
# USB names come from hwdata rather than from linux-usb.org, because the file
# served there carries no licence header and the absence of one is not
# permission. hwdata ships the same list and states a licence for it: GPL
# version 2 or later, or the XFree86 1.0 licence.
#
# Only ids this repository already references are here. The upstream lists are
# two megabytes of hardware nothing here drives.
"""


def fetch(url):
    """The list, however this machine can read it.

    Same fallback as the Mac table: urllib carries its own trust store and a
    network that inspects TLS refuses it, while curl uses the system's."""
    try:
        with urllib.request.urlopen(url, timeout=40) as r:
            return r.read().decode('utf-8', 'replace')
    except urllib.error.URLError as first:
        import shutil
        import subprocess
        if not shutil.which('curl'):
            raise
        got = subprocess.run(['curl', '-sS', '--max-time', '40', url],
                             capture_output=True, text=True)
        if got.returncode != 0 or not got.stdout.strip():
            raise SystemExit(f'{first}\nand curl: {got.stderr.strip()}')
        return got.stdout


TOP = re.compile(r'^([0-9a-fA-F]{4})\s+(.+?)\s*$')
SECOND = re.compile(r'^\t([0-9a-fA-F]{4})\s+(.+?)\s*$')


def parse(text):
    """(vendors, devices) from a pci.ids or usb.ids file.

    Both files have the same shape: a vendor at the left margin, its devices
    indented one tab, subsystems two. Two tabs are ignored - a subsystem names
    the board a chip was soldered to, not the chip."""
    vendors, devices, vendor = {}, {}, None
    for line in text.splitlines():
        if not line or line.startswith('#'):
            continue
        top = TOP.match(line)
        if top:
            vendor = top.group(1).lower()
            vendors[vendor] = top.group(2)
            continue
        if vendor and not line.startswith('\t\t'):
            device = SECOND.match(line)
            if device:
                devices[f'{vendor}:{device.group(1).lower()}'] = device.group(2)
    return vendors, devices


def wanted():
    """Every id this repository refers to, by bus."""
    pci, usb = set(), set()
    for driver in ocgen.read_toml('data/hardware.toml')['driver']:
        target = usb if driver['bus'] == 'usb' else pci
        target.update(i.lower() for i in driver['ids'] if ':' in i)
    for card in ocgen.read_toml('data/gpu.toml')['card']:
        pci.add(card['id'].lower())
    for reader in ocgen.read_toml('data/cardreader.toml')['device']:
        pci.add(reader['id'].lower())
    framebuffers = ocgen.read_toml('data/framebuffer.toml')
    for native in framebuffers.get('native', []):
        pci.update(i.lower() for i in native.get('ids', []) if ':' in i)
    return pci, usb


def refresh():
    pci_wanted, usb_wanted = wanted()
    rows, vendors = [], {}
    for source, url, ids in (('pci', PCI_SOURCE, pci_wanted),
                             ('usb', USB_SOURCE, usb_wanted)):
        found_vendors, found_devices = parse(fetch(url))
        for device_id in sorted(ids):
            vendor = device_id.split(':')[0]
            if vendor in found_vendors:
                vendors[vendor] = found_vendors[vendor]
            if device_id in found_devices:
                rows.append({'id': device_id, 'bus': source,
                             'name': found_devices[device_id]})
    named = {r['id'] for r in rows}
    missing = sorted((pci_wanted | usb_wanted) - named)
    tree = {
        'source': {'pci': PCI_SOURCE, 'usb': USB_SOURCE},
        'vendor': [{'id': v, 'name': n} for v, n in sorted(vendors.items())],
        'device': rows,
        # said rather than hidden: an id the upstream lists do not carry is
        # still an id this repository drives, and the catalogue shows it by id
        'unnamed': missing,
    }
    ocgen.write_toml(TABLE, tree, HEADER)
    print(f'{len(rows)} named, {len(missing)} not in the upstream lists, '
          f'{len(vendors)} vendors -> {TABLE}')
    return 0


_cache = None


def table():
    global _cache
    if _cache is None:
        _cache = ocgen.read_toml(TABLE) if TABLE.exists() else {}
    return _cache


def names():
    return {r['id']: r['name'] for r in table().get('device', [])}


def vendors():
    return {r['id']: r['name'] for r in table().get('vendor', [])}


def describe(device_id):
    """(vendor, name) for an id, either of which may be None."""
    device_id = (device_id or '').lower()
    return (vendors().get(device_id.split(':')[0]), names().get(device_id))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--refresh', action='store_true', help='ask upstream (network)')
    ap.add_argument('id', nargs='?', help='one device id')
    a = ap.parse_args(argv)
    if a.refresh:
        return refresh()
    have = table()
    if not have:
        sys.exit(f'{TABLE} does not exist yet; run --refresh')
    if a.id:
        vendor, name = describe(a.id)
        print(f'{a.id}: {name or "not in the upstream lists"}'
              + (f'  [{vendor}]' if vendor else ''))
        return 0
    print(f'{len(have["device"])} named ids, {len(have["vendor"])} vendors, '
          f'{len(have.get("unnamed", []))} unnamed')
    return 0


if __name__ == '__main__':
    sys.exit(main())
