"""Build data/hardware.toml from the kexts themselves.

The mapping from a PCI or USB id to the kext that drives it is not written by
hand and not copied out of a guide. Every kext already declares exactly which
devices it binds to, in IOPCIPrimaryMatch, IOPCIMatch or idVendor/idProduct, so
the table is read straight out of those and carries the kext version it came
from. When a kext is updated the table is regenerated and the diff shows which
devices it gained or lost.

    python3 tools/hwtable.py <directory-of-kexts> [--out data/hardware.toml]
"""
import argparse
import collections
import glob
import os
import plistlib
import re
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ocgen

# What each kext is for, in the words a person choosing hardware would use.
ROLES = {
    'IntelMausi': ('ethernet', 'Intel Ethernet'),
    'IntelSnowMausi': ('ethernet', 'Intel Ethernet, Snow Leopard'),
    'RealtekRTL8111': ('ethernet', 'Realtek Gigabit Ethernet'),
    'LucyRTL8125Ethernet': ('ethernet', 'Realtek 2.5G Ethernet'),
    'AtherosE2200Ethernet': ('ethernet', 'Atheros/Killer Ethernet'),
    'AirportItlwm': ('wifi', 'Intel Wi-Fi'),
    'IntelBluetoothFirmware': ('bluetooth', 'Intel Bluetooth'),
    'IntelBluetoothInjector': ('bluetooth', 'Intel Bluetooth, Monterey and older'),
    'BrcmPatchRAM3': ('bluetooth', 'Broadcom Bluetooth, Big Sur and newer'),
    'BrcmPatchRAM2': ('bluetooth', 'Broadcom Bluetooth, Catalina and older'),
    'BrcmBluetoothInjector': ('bluetooth', 'Broadcom Bluetooth injector'),
}


def pci_ids(value):
    """IOPCIPrimaryMatch packs device and vendor into one 0xDDDDVVVV word."""
    out = set()
    for tok in re.findall(r'0x[0-9a-fA-F]{8}', value or ''):
        n = int(tok, 16)
        out.add(f'{n & 0xffff:04x}:{n >> 16:04x}')
    return out


def scan(root):
    found = collections.defaultdict(lambda: {'pci': set(), 'usb': set()})
    versions = {}
    for path in sorted(glob.glob(f'{root}/**/*.kext', recursive=True)):
        if '__MACOSX' in path or path.count('.kext') > 1:
            continue
        name = Path(path).stem
        if name not in ROLES:
            continue
        try:
            with open(f'{path}/Contents/Info.plist', 'rb') as fh:
                info = plistlib.load(fh)
        except (OSError, plistlib.InvalidFileException):
            continue
        versions[name] = info.get('CFBundleShortVersionString', '')
        for p in info.get('IOKitPersonalities', {}).values():
            found[name]['pci'] |= pci_ids(p.get('IOPCIPrimaryMatch', ''))
            found[name]['pci'] |= pci_ids(p.get('IOPCIMatch', ''))
            v, d = p.get('idVendor'), p.get('idProduct')
            if isinstance(v, int) and isinstance(d, int):
                found[name]['usb'].add(f'{v:04x}:{d:04x}')
    return found, versions


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('kexts', help='directory holding the unpacked kexts')
    ap.add_argument('--out', default='data/hardware.toml')
    a = ap.parse_args()

    found, versions = scan(a.kexts)
    if not found:
        sys.exit(f'no known kexts under {a.kexts}')

    entries = []
    for name in sorted(found):
        role, label = ROLES[name]
        for bus in ('pci', 'usb'):
            ids = sorted(found[name][bus])
            if ids:
                entries.append({'kext': f'{name}.kext', 'role': role, 'label': label,
                                'version': versions.get(name, ''), 'bus': bus, 'ids': ids})
    ocgen.write_toml(Path(a.out), {'driver': entries},
                     '# Which kext drives which device.\n'
                     '#\n'
                     '# Generated by tools/hwtable.py from the kexts themselves: every id\n'
                     '# here comes out of that kext\'s own IOPCIPrimaryMatch, IOPCIMatch or\n'
                     '# idVendor/idProduct, so it says what the driver actually binds to\n'
                     '# rather than what a guide remembers. Regenerate after updating a\n'
                     '# kext; the diff is the list of devices it gained or lost.')
    total = sum(len(e['ids']) for e in entries)
    print(f'  {len(entries)} driver entries, {total} device ids')
    for e in entries:
        print(f'      {e["kext"]:30s} {e["role"]:9s} {e["bus"]} {len(e["ids"]):4d}  v{e["version"]}')


if __name__ == '__main__':
    main()
