"""Vendored kexts and their upstream provenance.

The kexts in EFI/OC/Kexts are the source of truth. A build never reaches the
network: a clone already contains everything needed, which matters because the
EFI is usually prepared on a machine that is not the one being installed, and
often is not online. `--update` is the only thing that talks to GitHub, and it
only refreshes what is actually older than upstream.

    python3 tools/kexts.py check      # verify the tree against vendor/kexts.lock
    python3 tools/kexts.py relock     # rewrite the lock from the current tree
    python3 tools/kexts.py outdated   # ask GitHub what is newer (network)
"""
import argparse
import hashlib
import json
import os
import plistlib
import sys
import urllib.error
import urllib.request
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ocgen

KEXTS = Path('EFI/OC/Kexts')
LOCK = Path('vendor/kexts.lock')

# Which upstream release a bundle comes from. Several kexts ship inside one
# release, so the mapping is bundle -> repo, not repo -> bundle. Verified against
# the GitHub API; the ones marked None publish no releases and are vendored only.
UPSTREAM = {
    'Lilu.kext': 'acidanthera/Lilu',
    'VirtualSMC.kext': 'acidanthera/VirtualSMC',
    'SMCProcessor.kext': 'acidanthera/VirtualSMC',
    'SMCSuperIO.kext': 'acidanthera/VirtualSMC',
    'SMCBatteryManager.kext': 'acidanthera/VirtualSMC',
    'SMCDellSensors.kext': 'acidanthera/VirtualSMC',
    'WhateverGreen.kext': 'acidanthera/WhateverGreen',
    'AppleALC.kext': 'acidanthera/AppleALC',
    'VoodooPS2Controller.kext': 'acidanthera/VoodooPS2',
    'ECEnabler.kext': '1Revenger1/ECEnabler',
    'USBToolBox.kext': 'USBToolBox/kext',
    'IntelMausi.kext': 'acidanthera/IntelMausi',
    'RealtekRTL8111.kext': 'Mieze/RTL8111_driver_for_OS_X',
    'LucyRTL8125Ethernet.kext': 'Mieze/LucyRTL8125Ethernet',
    'AtherosE2200Ethernet.kext': 'Mieze/AtherosE2200Ethernet',
    'IntelBluetoothFirmware.kext': 'OpenIntelWireless/IntelBluetoothFirmware',
    'IntelBluetoothInjector.kext': 'OpenIntelWireless/IntelBluetoothFirmware',
    'IntelBTPatcher.kext': 'OpenIntelWireless/IntelBluetoothFirmware',
    'BrcmFirmwareData.kext': 'acidanthera/BrcmPatchRAM',
    'BrcmPatchRAM.kext': 'acidanthera/BrcmPatchRAM',
    'BrcmPatchRAM2.kext': 'acidanthera/BrcmPatchRAM',
    'BrcmPatchRAM3.kext': 'acidanthera/BrcmPatchRAM',
    'BrcmBluetoothInjector.kext': 'acidanthera/BrcmPatchRAM',
    'BlueToolFixup.kext': 'acidanthera/BrcmPatchRAM',
    'AirportBrcmFixup.kext': 'acidanthera/AirportBrcmFixup',
    'AirportItlwm.kext': 'OpenIntelWireless/itlwm',
    'NVMeFix.kext': 'acidanthera/NVMeFix',
    'UTBDefault.kext': 'USBToolBox/kext',
    'AMDRyzenCPUPowerManagement.kext': 'trulyspinach/SMCAMDProcessor',
    'SMCAMDProcessor.kext': 'trulyspinach/SMCAMDProcessor',
    'AppleMCEReporterDisabler.kext': None,
    'USBInjectAll.kext': None,
    'XHCI-unsupported.kext': None,
    'XLNCUSBFix.kext': None,
    'telemetrap.kext': None,
}


def digest(bundle):
    """Hash of a kext bundle: every file, path included, order fixed."""
    h = hashlib.sha256()
    for p in sorted(bundle.rglob('*')):
        if p.is_file():
            h.update(str(p.relative_to(bundle)).encode())
            h.update(p.read_bytes())
    return h.hexdigest()


def version(bundle):
    """Some kexts set only CFBundleVersion, so fall back rather than report blank."""
    info = bundle / 'Contents' / 'Info.plist'
    if not info.exists():
        return ''
    with open(info, 'rb') as fh:
        d = plistlib.load(fh)
    return d.get('CFBundleShortVersionString') or d.get('CFBundleVersion') or ''


def scan():
    out = {}
    for b in sorted(KEXTS.glob('*.kext')):
        out[b.name] = {'version': version(b), 'sha256': digest(b),
                       'upstream': UPSTREAM.get(b.name) or ''}
    return out


def latest(repo):
    try:
        with urllib.request.urlopen(f'https://api.github.com/repos/{repo}/releases/latest') as r:
            return json.load(r).get('tag_name', '')
    except urllib.error.URLError:
        return ''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('action', choices=('check', 'relock', 'outdated'))
    a = ap.parse_args()
    have = scan()

    if a.action == 'relock':
        ocgen.write_toml(LOCK, {'kext': have},
                         '# Vendored kexts. Generated by tools/kexts.py relock.\n'
                         '# sha256 covers every file in the bundle, so a partial\n'
                         '# or truncated checkout is caught before it is copied.\n')
        print(f'  locked {len(have)} kexts -> {LOCK}')
        return 0

    if a.action == 'check':
        if not LOCK.exists():
            sys.exit(f'{LOCK} missing; run: python3 tools/kexts.py relock')
        want = ocgen.read_toml(LOCK)['kext']
        bad = 0
        for name in sorted(set(want) | set(have)):
            if name not in have:
                print(f'  MISSING  {name}'); bad += 1
            elif name not in want:
                print(f'  UNLOCKED {name}'); bad += 1
            elif have[name]['sha256'] != want[name]['sha256']:
                print(f'  CHANGED  {name}  {want[name]["sha256"][:12]} -> '
                      f'{have[name]["sha256"][:12]}'); bad += 1
        print(f'  {len(have) - bad}/{len(have)} kexts match the lock')
        return 1 if bad else 0

    width = max(len(k) for k in have)
    stale = 0
    for name, info in have.items():
        repo = info['upstream']
        if not repo:
            print(f'  {name:{width}s} {info["version"]:10s} vendored only')
            continue
        up = latest(repo) or '?'
        # tags and bundle versions are numbered differently by some projects, so
        # this is a prompt to look rather than a verdict
        same = up in ('?', info['version']) or up.lstrip('v') == info['version']
        mark = '' if same else '  <- differs from upstream tag'
        stale += bool(mark)
        print(f'  {name:{width}s} {info["version"]:10s} {repo} {up}{mark}')
    print(f'\n  {stale} kext(s) differ from their upstream tag; check each before updating')
    return 0


if __name__ == '__main__':
    sys.exit(main())
