"""Which macOS a real Mac can run, from Apple's own metadata.

Every other table here is about a machine somebody is converting. This one is
about the machine they may be sitting at: a Mac reports none of the hardware
those tables key on, and the honest thing to show instead is what Apple says
about that model.

The source is the endpoint Apple publishes for device management:

    https://gdmf.apple.com/v2/pmv

It lists every macOS line Apple still serves, and for each one the machines it
runs on - by the board name a Mac reports of itself, "J314sAP" on Apple silicon
and "Mac-1E7E29AD0135F9BC" on Intel. So the floor is the oldest line that names
a board and the ceiling is the newest, and both are read rather than remembered.

    python3 tools/mactable.py --refresh     # network
    python3 tools/mactable.py               # what the table says now

What it cannot say: Apple only publishes the lines it still serves. A Mac that
shipped with Sierra and stopped at Monterey reads as "12 and newer" here,
because 11 is as far back as the endpoint goes. The floor is therefore the
oldest *still-served* release, and the table says so rather than implying it is
the release the machine shipped with.
"""
import argparse
import json
import os
import sys
import urllib.request
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ocgen

SOURCE = 'https://gdmf.apple.com/v2/pmv'
TABLE = Path('data/mac.toml')

HEADER = """# Which macOS a real Mac can run.

#
# Generated by tools/mactable.py --refresh from Apple's own device-management
# metadata at gdmf.apple.com/v2/pmv, which lists each macOS line Apple still
# serves together with the machines it runs on. A board is named the way the
# machine names itself: J314sAP on Apple silicon, Mac-... on Intel.
#
# `floor` is the oldest line that still lists the board, which is not the same
# as the release it shipped with: Apple stops publishing a line and it leaves
# this file. An empty `ceiling` means the newest line still lists it.
"""


def fetch(url=SOURCE):
    """The endpoint, read however this machine can read it.

    urllib carries its own idea of who to trust, and on a network that
    inspects TLS - a workplace proxy, and this was found on one - it refuses a
    certificate the rest of the machine accepts. curl uses the system's trust
    store, so where urllib cannot get through, it can."""
    try:
        with urllib.request.urlopen(url, timeout=30) as r:
            return json.loads(r.read().decode('utf-8', 'replace'))
    except urllib.error.URLError as first:
        import shutil
        import subprocess
        if not shutil.which('curl'):
            raise
        got = subprocess.run(['curl', '-sS', '--max-time', '30', url],
                             capture_output=True, text=True)
        if got.returncode != 0 or not got.stdout.strip():
            raise SystemExit(f'{first}\nand curl: {got.stderr.strip()}')
        return json.loads(got.stdout)


def collect(payload):
    """{board: {'floor': major, 'ceiling': major or None, 'lines': [...]}}.

    Sorted by the major version as a number, because "9" sorts after "26" as a
    string and the floor would come out as the newest release."""
    lines = payload.get('PublicAssetSets', {}).get('macOS', [])
    ordered = sorted(lines, key=lambda e: [int(x) for x in
                                           e['ProductVersion'].split('.')])
    if not ordered:
        return {}, []
    newest = ordered[-1]['ProductVersion']
    boards = {}
    for entry in ordered:
        version = entry['ProductVersion']
        for board in entry.get('SupportedDevices', []):
            boards.setdefault(board, []).append(version)
    out = {}
    for board, versions in boards.items():
        out[board] = {
            'floor': versions[0].split('.')[0],
            # the newest line lists it, so there is no ceiling to state
            'ceiling': None if versions[-1] == newest else versions[-1].split('.')[0],
            'lines': versions,
        }
    return out, [e['ProductVersion'] for e in ordered]


def refresh():
    boards, lines = collect(fetch())
    if not boards:
        sys.exit('the endpoint listed no machines')
    tree = {
        'source': SOURCE,
        'lines': lines,
        'mac': [{'board': board, 'floor': facts['floor'],
                 'ceiling': facts['ceiling'] or '', 'lines': facts['lines']}
                for board, facts in sorted(boards.items())],
    }
    ocgen.write_toml(TABLE, tree, HEADER)
    print(f'{len(boards)} machines across {len(lines)} macOS lines -> {TABLE}')
    return 0


def table():
    return ocgen.read_toml(TABLE) if TABLE.exists() else {}


def window(board):
    """(floor, ceiling or None) for one board, or None if it is not listed."""
    if not board:
        return None
    for row in table().get('mac', []):
        if row['board'].lower() == board.lower():
            return row['floor'], (row['ceiling'] or None)
    return None


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--refresh', action='store_true',
                    help="ask Apple and rewrite the table (network)")
    ap.add_argument('--board', help='what the table says about one board')
    a = ap.parse_args(argv)
    if a.refresh:
        return refresh()
    have = table()
    if not have:
        sys.exit(f'{TABLE} does not exist yet; run --refresh')
    if a.board:
        found = window(a.board)
        print(f'{a.board}: not listed' if not found else
              f'{a.board}: macOS {found[0]} and newer' if not found[1] else
              f'{a.board}: macOS {found[0]} to {found[1]}')
        return 0
    print(f'{len(have["mac"])} machines across {len(have["lines"])} macOS lines')
    print('  ' + ', '.join(have['lines']))
    return 0


if __name__ == '__main__':
    sys.exit(main())
