"""What OpenCore Legacy Patcher restores, and from which macOS.

A card that macOS stopped driving is not always the end of it. OCLP's root
patches put the old drivers back, and its own documentation states which
families it does that for and from which release:

    https://dortania.github.io/OpenCore-Legacy-Patcher/PATCHEXPLAIN.html

    NVIDIA Kepler Graphics Acceleration Patches (12.0+)
    Intel Haswell Graphics Acceleration Patches (13.0+)
    ...

So a GTX 680 reads "macOS 10.8 to Big Sur 11" natively, and "Monterey 12 and
newer with OCLP" beside it. Both are facts from published pages; neither is a
promise that a given machine will boot.

Two things this is not:

  * Not part of a build. OCLP patches a macOS installation after the fact. This
    repository writes an EFI and touches none of that.
  * Not a statement about Hackintoshes. OCLP is written for real Macs. Its
    documentation says nothing either way about a PC running macOS, and neither
    does this table.

    python3 tools/oclptable.py --refresh    # network
    python3 tools/oclptable.py              # what the table says now
"""
import argparse
import html
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ocgen

BASE = 'https://dortania.github.io/OpenCore-Legacy-Patcher'
SOURCE = f'{BASE}/PATCHEXPLAIN.html'
# The patch pages say where a patch set starts and never where it stops, so the
# ceiling comes from the shape of the documentation instead: OCLP publishes one
# page per macOS it has added support for - MONTEREY-DROP, VENTURA-DROP,
# SONOMA-DROP, SEQUOIA-DROP - and the newest of those is as far as it goes.
CEILING_FROM = f'{BASE}/MODELS.html'
TABLE = Path('data/oclp.toml')

HEADER = """# What OpenCore Legacy Patcher restores, and from which macOS.
#
# Generated by tools/oclptable.py --refresh from OCLP's own PATCHEXPLAIN page,
# which lists each patch set with the macOS it applies from.
#
# `ceiling_version` is not on the patch page - it says where each set starts and
# never where it stops. It is the newest macOS OCLP has published a support page
# for, which is as far as the project itself claims to go.
#
# `applies_to` is this repository's own name for the family, so a card can be
# joined to a patch set. The page writes "Kepler" and the GPU table keys on the
# chip prefix GK; the two vocabularies are matched here and nowhere else.
#
# OCLP patches an installed macOS, not an EFI. Nothing a build produces changes
# because of this table - it is here so a card that stops being supported can
# say what happens next.
"""

# The page names families in prose. These are the same families under the names
# the rest of this repository uses: a chip prefix for NVIDIA, an iGPU profile
# name for Intel, a card family for AMD. Nothing is decided here - only which
# of our rows a sentence of theirs is about.
FAMILY_NAMES = {
    'NVIDIA Kepler': {'nvidia_chips': ['GK']},
    'Intel Ivy Bridge': {'igpu_profiles': ['ivy-bridge']},
    'Intel Haswell': {'igpu_profiles': ['haswell']},
    'Intel Broadwell': {'igpu_profiles': ['broadwell']},
    'Intel Skylake': {'igpu_profiles': ['sky-lake']},
    'AMD Legacy Vega': {'card_families': ['Vega 10 series', 'Vega 20 series']},
    'AMD Legacy Polaris': {'card_families': ['Polaris 10 and 20 series']},
}

PATCH = re.compile(r'^(.+?Patches)\s*\(([\d.]+)\+?\)\s*$')


def fetch(url=SOURCE):
    """The page, however this machine can read it."""
    try:
        with urllib.request.urlopen(url, timeout=40) as r:
            return r.read().decode('utf-8', 'replace')
    except urllib.error.URLError as first:
        import shutil
        import subprocess
        if not shutil.which('curl'):
            raise
        got = subprocess.run(['curl', '-sS', '--max-time', '40', url],
                             capture_output=True, text=True)
        if got.returncode != 0 or not got.stdout.strip():
            raise SystemExit(f'{first}\nand curl: {got.stderr.strip()}')
        return got.stdout


DROP = re.compile(r'/OpenCore-Legacy-Patcher/([A-Z]+)-DROP\.html')


def ceiling(nav_page):
    """The newest macOS OCLP has published a support page for, or None."""
    names = {r['name'].upper().replace(' ', ''): r
             for r in ocgen.read_toml(Path('data/macos.toml'))['release']}
    found = [names[n] for n in set(DROP.findall(nav_page)) if n in names]
    if not found:
        return None
    newest = max(found, key=lambda r: r['darwin'])
    return {'name': newest['name'], 'version': str(newest['version'])}


def parse(page):
    """Each patch set, with the macOS it starts at and what it is about."""
    body = re.sub(r'<script.*?</script>', '', page, flags=re.S)
    lines = [l.strip() for l in
             html.unescape(re.sub(r'<[^>]+>', '\n', body)).splitlines() if l.strip()]
    out = []
    for n, line in enumerate(lines):
        found = PATCH.match(line)
        if not found:
            continue
        name, floor = found.group(1), found.group(2)
        reason = next((l[len('Reason:'):].strip() for l in lines[n + 1:n + 4]
                       if l.startswith('Reason:')), '')
        entry = {'name': name, 'from': floor, 'reason': reason,
                 'graphics': 'Graphics Acceleration' in name or 'non-Metal' in name}
        for prose, keys in FAMILY_NAMES.items():
            if name.startswith(prose):
                entry.update(keys)
                break
        out.append(entry)
    return out


def refresh():
    patches = parse(fetch())
    if len(patches) < 8:
        sys.exit(f'only found {len(patches)} patch sets; the page changed')
    top = ceiling(fetch(CEILING_FROM))
    if not top:
        sys.exit('found no macOS support pages; the documentation moved')
    claimed = [p for p in patches if p.get('nvidia_chips') or p.get('igpu_profiles')
               or p.get('card_families')]
    ocgen.write_toml(TABLE, {'source': SOURCE, 'ceiling_source': CEILING_FROM,
                             'ceiling_name': top['name'],
                             'ceiling_version': top['version'],
                             'patch': patches}, HEADER)
    print(f'{len(patches)} patch sets, {len(claimed)} matched to a family here, '
          f"up to {top['name']} {top['version']} -> {TABLE}")
    return 0


_cache = None


def table():
    global _cache
    if _cache is None:
        _cache = ocgen.read_toml(TABLE) if TABLE.exists() else {}
    return _cache


def upper_bound():
    """(name, version) of the newest macOS OCLP supports, or None."""
    have = table()
    if not have.get('ceiling_version'):
        return None
    return have['ceiling_name'], have['ceiling_version']


def for_nvidia(chip_prefix):
    """The patch set covering an NVIDIA chip family, or None."""
    for patch in table().get('patch', []):
        if chip_prefix in patch.get('nvidia_chips', []):
            return patch
    return None


def for_igpu(profile):
    """The patch set covering an Intel iGPU generation, or None."""
    for patch in table().get('patch', []):
        if profile in patch.get('igpu_profiles', []):
            return patch
    return None


def for_card_family(family):
    """The patch set covering an AMD card family, or None."""
    for patch in table().get('patch', []):
        if family in patch.get('card_families', []):
            return patch
    return None


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--refresh', action='store_true', help='ask the page (network)')
    a = ap.parse_args(argv)
    if a.refresh:
        return refresh()
    have = table()
    if not have:
        sys.exit(f'{TABLE} does not exist yet; run --refresh')
    for patch in have['patch']:
        joins = (patch.get('nvidia_chips') or patch.get('igpu_profiles')
                 or patch.get('card_families') or [])
        print(f"  macOS {patch['from']}+  {patch['name'][:52]:<54} "
              f"{', '.join(joins) or '-'}")
    return 0


if __name__ == '__main__':
    sys.exit(main())
