"""Which Mac a config pretends to be, and how far that identity goes.

A config picks an identity - `SystemProductName`, MacBookPro14,1 - and macOS
decides what it will install from that. The hardware can be perfect and the
install still refuse, because Apple stopped serving that model three releases
ago. Nothing here knew that: the machine page says as much, in the sentence
about the SMBIOS having a ceiling of its own that is not recorded.

Two tables, joined:

  * the identity's board id, from acidanthera's AppleModels database, which is
    the same data OpenCore itself uses to fill the SMBIOS in,
  * that board's newest macOS, from `boards.json` - macrecovery's own board
    list, already vendored with OpenCore for the Recovery tab.

    python3 tools/smbios.py --refresh    # network; rewrites data/smbios.toml
    python3 tools/smbios.py              # what every profile's identity reaches

Not from Apple's device-management metadata. That endpoint lists, per macOS
line, the machines that line is still served to, which is a narrower thing than
"can run": MacBookPro16,1 appears only under Big Sur there and plainly runs
more than Big Sur. `boards.json` answers the question that was actually asked.
"""
import argparse
import json
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import ocgen
import recovery

TABLE = Path('data/smbios.toml')
PROFILES = Path('profiles/cpu')
API = 'https://api.github.com/repos/acidanthera/OpenCorePkg/contents/AppleModels/DataBase'
RAW = ('https://raw.githubusercontent.com/acidanthera/OpenCorePkg/master/'
       'AppleModels/DataBase')
FAMILIES = ('MacBook', 'MacBookAir', 'MacBookPro', 'MacPro', 'Macmini',
            'Xserve', 'iMac', 'iMacPro')

HEADER = """# The board id behind each Mac identity a config can claim.
#
# Generated by tools/smbios.py --refresh from acidanthera's AppleModels
# database, which is where OpenCore itself takes the SMBIOS fields from. The
# board is what macOS matches on, so it is the join to how far an identity
# goes: tools/recovery.py reads the newest macOS each board is offered from
# macrecovery's own boards.json.
#
# A model can carry more than one board - iMac17,1 has three - and they are
# kept in the order the database lists them.
"""


def _get(url):
    """Read a URL, however this machine can. Same fallback as every fetcher here."""
    import urllib.error
    import urllib.request
    try:
        with urllib.request.urlopen(url, timeout=60) as r:
            return r.read()
    except urllib.error.URLError as first:
        import shutil
        import subprocess
        if not shutil.which('curl'):
            raise
        got = subprocess.run(['curl', '-sSL', '--max-time', '120', url],
                             capture_output=True)
        if got.returncode != 0 or not got.stdout:
            raise SystemExit(f'{first}\nand curl: {got.stderr.decode()[:200]}')
        return got.stdout


def boards_in(text):
    """The board ids in one model file, scalar or list.

    Both spellings are in the database and the list one is not the rare case:
    iMac17,1 has three boards, and a parser that only reads the scalar form
    drops that model silently."""
    scalar = re.findall(r'^BoardProduct:\s*"([^"]+)"\s*$', text, re.M)
    if scalar:
        return scalar
    block = re.search(r'^BoardProduct:\s*\n((?:\s+-?\s*"[^"]+"\s*\n)+)', text, re.M)
    return re.findall(r'"([^"]+)"', block.group(1)) if block else []


def parse(text):
    """One model, or None when the file names no identity."""
    model = re.search(r'^SystemProductName:\s*"([^"]+)"', text, re.M)
    boards = boards_in(text)
    if not model or not boards:
        return None
    return {'model': model.group(1), 'boards': boards}


def refresh():
    """Fetch every model file and rewrite the table."""
    rows = []
    for family in FAMILIES:
        listed = json.loads(_get(f'{API}/{family}?ref=master'))
        for entry in listed:
            if not entry['name'].endswith('.yaml'):
                continue
            got = parse(_get(f'{RAW}/{family}/{entry["name"]}').decode('utf-8',
                                                                      'replace'))
            if got:
                got['family'] = family
                rows.append(got)
    rows.sort(key=lambda r: r['model'])
    lines = [HEADER, f'source = "{RAW}"', f'models = {len(rows)}', '']
    for row in rows:
        lines.append('[[model]]')
        lines.append(f'name = {json.dumps(row["model"])}')
        lines.append(f'family = {json.dumps(row["family"])}')
        lines.append('boards = [' + ', '.join(json.dumps(b) for b in row['boards'])
                     + ']')
        lines.append('')
    TABLE.write_text('\n'.join(lines), encoding='utf-8')
    return len(rows)


def table():
    return ocgen.read_toml(TABLE).get('model', []) if TABLE.exists() else []


def boards(model):
    """The board ids for one identity, or []."""
    for row in table():
        if row['name'] == model:
            return row['boards']
    return []


def reach(model):
    """How far this identity goes: (version, name) or (None, complaint).

    "latest" is what macrecovery's list says for the boards Apple keeps
    current, and it is passed through as that word rather than turned into a
    number nothing here knows."""
    found = boards(model)
    if not found:
        return None, f'{model} is not in the model table'
    served = recovery.served()
    seen = [served[b] for b in found if b in served]
    if not seen:
        return None, f'no board of {model} is in macrecovery\'s list'
    if any(v == 'latest' for v in seen):
        return 'latest', 'whatever Apple is serving now'
    best = max(seen, key=lambda v: [int(n) for n in v.split('.')])
    return best, _named(best)


def _named(version):
    short = version.rsplit('.', 1)[0] if version.startswith('10.') else \
        version.split('.')[0]
    for row in ocgen.read_toml(Path('data/macos.toml'))['release']:
        if row['version'] == short:
            return f"{row['name']} {version}"
    return version


def reaches(model, wanted):
    """Whether this identity is offered the macOS asked for.

    `wanted` is a marketing version - "26", "15", "10.15". Returns
    (True/False, sentence)."""
    version, said = reach(model)
    if version is None:
        return None, said
    if version == 'latest':
        return True, 'one Apple keeps current, so whatever is newest'
    top = [int(n) for n in version.split('.')]
    ask = [int(n) for n in str(wanted).split('.')]
    fits = top[:len(ask)] >= ask
    return fits, f'served up to {said}'


def higher(wanted):
    """The identities that do reach that macOS, newest last."""
    out = []
    for row in table():
        fits, _ = reaches(row['name'], wanted)
        if fits:
            out.append(row['name'])
    return out


FIELD = Path('data/field.toml')


def reported(model, wanted):
    """What somebody has actually observed about this identity on this macOS.

    The tables say what Apple serves. Whether an install completes on hardware
    that is not that Mac is a different question, and the only answer to it is
    somebody having run it."""
    if not FIELD.exists():
        return []
    out = []
    for row in ocgen.read_toml(FIELD).get('smbios', []):
        if row.get('model') != model:
            continue
        if str(row.get('macos')) != str(wanted):
            continue
        out.append(row)
    return out


LAPTOPS = ('MacBook', 'MacBookAir', 'MacBookPro')


def _number(model):
    """(major, minor) out of "MacBookPro16,1", for ordering within a family."""
    found = re.search(r'(\d+),(\d+)$', model)
    return (int(found.group(1)), int(found.group(2))) if found else (0, 0)


def _family(model):
    return re.sub(r'\d+,\d+$', '', model)


def suggest(identity, wanted, limit=3):
    """Identities that are served `wanted` and are the nearest thing to this one.

    Nearest, not newest: the closest model that is still served keeps the most
    of what the profile was written around. Same family first - a laptop stays
    a laptop - then anything of the same shape, because a family can run out
    before the release does."""
    served = set(higher(wanted))
    if not served:
        return []
    family = _family(identity)
    laptop = family in LAPTOPS
    here = _number(identity)

    same = sorted((m for m in served if _family(m) == family and _number(m) > here),
                  key=_number)
    shape = sorted((m for m in served
                    if (_family(m) in LAPTOPS) == laptop
                    and m not in same and m != identity),
                   key=lambda m: (_family(m), _number(m)))
    return (same + shape)[:limit]


def profile_identity(text):
    """The SystemProductName a profile writes, or None."""
    found = re.search(r'^SystemProductName\s*=\s*"([^"]+)"', text, re.M)
    return found.group(1) if found else None


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--refresh', action='store_true',
                    help='fetch the model database and rewrite the table (network)')
    ap.add_argument('--macos', help='name the identities that reach this macOS')
    a = ap.parse_args(argv)

    if a.refresh:
        print(f'{refresh()} models -> {TABLE}')
        return 0

    if not table():
        print(f'{TABLE} is not here yet; run --refresh')
        return 1

    if a.macos:
        named = higher(a.macos)
        print(f'{len(named)} identities reach macOS {a.macos}')
        for name in named:
            version, said = reach(name)
            print(f'  {name:18} {said}')
        return 0

    print(f'{"identity":18} {"used by":8} reaches')
    seen = {}
    for profile in sorted(PROFILES.rglob('*.toml')):
        identity = profile_identity(profile.read_text(encoding='utf-8'))
        if identity:
            seen.setdefault(identity, []).append(profile.stem)
    for identity, where in sorted(seen.items()):
        version, said = reach(identity)
        print(f'  {identity:18} {len(where):3} {"":4} {said}')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
